const playlist = [
  { title: "I was made for loving you", band: "Kiss" },
  { title: "Born dead", band: "Death" },
  { title: "Derech Hashalom", band: "Peer Tasi" },
  { title: "Coco Jambo", band: "Mr President" },
  { title: "Sweet child of mine", band: "Gun's and roses" },
  { title: "Californication", band: "Red Hot Chilli peppers" },
  { title: `Africa`, band: `Toto` },
  { title: `Push It`, band: `Salt N Pepa` },
  { title: "From skin to liquid", band: "Cannibal Corpse" },
  { title: "Oops I did it again", band: "Britney Spears" },
  { title: `Toxic`, band: `Britney Spears` },
  { title: "Because I Got High", band: "Afroman" },
  { title: `Hopa`, band: `Omer Adam` },
  { title: "Lets Get It On", band: "Marvin Gaye" },
  { title: `Zikukim`, band: `Moshe Perez` },
  { title: `One`, band: `Dua Lipa` },
  { title: "Juicy", band: "The Notorious B.I.G." },
  { title: `Push It`, band: `Salt N Pepa` },
  { title: "Hermetico ", band: "Balkan Beat Box" },
  { title: "Crazy", band: "Seal" },
];
